language: php

php:
  - 7.0
  - 7.1

sudo: false

env:
  global:
    - PHPUNIT=1

matrix:
  fast_finish: true

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction

script:
  - sh -c "./bin/phpunit"